In [1]:
import numpy as np

In [3]:
np.arange(1000000) + 5 [:]

TypeError: 'int' object is not subscriptable

In [4]:
l=range(1000000)

In [5]:
import numpy as np

In [6]:
d=np.arange(1000000)

In [7]:
%time for i in range (1,10): r=[x*2 for x in l]

Wall time: 1.5 s
Parser   : 130 ms


In [8]:
%time for i in range (1,10): r=d*2

Wall time: 88.9 ms


In [9]:
%time for i in range (1,10): r=d*2

Wall time: 30 ms


In [10]:
import numpy as np

In [11]:
x=np.zeros((4,4))

In [12]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
l=[1,4,5,7]

In [16]:
np.array(1)

array(1)

In [17]:
np.array(l)

array([1, 4, 5, 7])

In [18]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [19]:
x.shape

(4, 4)

In [20]:
x=np.zeros((10,10))

In [21]:
x.shape

(10, 10)

In [22]:
y=x.reshape((2,2,5,5))

In [23]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [24]:
y.dtype

dtype('float64')

In [25]:
y.ndim

4

In [26]:
a=np.random.randn((10))

In [27]:
b=np.random.randn((10))

In [28]:
a

array([-0.49213649,  1.09010872, -0.90034166,  1.88468782, -0.01321673,
       -0.88701961, -1.08217336,  2.86028853,  2.18501715,  0.29302879])

In [29]:
b

array([ 1.81230975, -0.15286651,  0.83402394, -1.1031075 , -1.28562728,
       -0.39667841,  2.36380705,  1.81913598,  0.90552884, -1.47858332])

In [30]:
a+b

array([ 1.32017327,  0.93724222, -0.06631772,  0.78158031, -1.29884401,
       -1.28369803,  1.28163369,  4.67942452,  3.09054599, -1.18555453])

In [31]:
a-b

array([-2.30444624,  1.24297523, -1.7343656 ,  2.98779532,  1.27241055,
       -0.4903412 , -3.44598041,  1.04115255,  1.27948831,  1.77161211])

In [32]:
2*a

array([-0.98427298,  2.18021744, -1.80068332,  3.76937563, -0.02643345,
       -1.77403923, -2.16434672,  5.72057707,  4.37003429,  0.58605758])

In [33]:
1/a

array([ -2.03195663,   0.91733969,  -1.11068947,   0.53059185,
       -75.6616997 ,  -1.12737079,  -0.92406636,   0.34961508,
         0.45766231,   3.41263396])

In [34]:
a>0

array([False,  True, False,  True, False, False, False,  True,  True,
        True])

In [35]:
a[a>0]

array([1.09010872, 1.88468782, 2.86028853, 2.18501715, 0.29302879])

In [36]:
x=np.array([1,7,9,8,5])

In [37]:
x[4]

5

In [38]:
x[x>5]

array([7, 9, 8])

In [39]:
x[[2,1]]

array([9, 7])

In [40]:
x=np.random.randn(10,10)

In [41]:
x

array([[ 1.49830411,  1.95394949,  0.53686325, -0.94964002, -1.1491122 ,
         2.75855392, -0.69427643, -0.7667491 ,  0.39207593,  0.37116246],
       [-0.30972882, -0.62845745,  1.79749271,  0.24256362,  0.03158585,
         0.6650032 ,  0.37460497,  0.04662303,  0.02566594,  0.49583538],
       [ 1.53775336, -0.45566752,  0.54780978, -0.7095128 ,  0.48643768,
        -0.75414241, -0.22444344,  0.50481633, -1.8045399 , -2.0467774 ],
       [-0.14118574, -1.86607762, -0.2742129 , -0.29064077, -0.53258824,
        -1.61506176,  1.0605039 , -0.62701008, -0.97516007, -2.00734035],
       [ 1.45610833, -0.98545718,  0.8000099 ,  1.32246408,  0.22499403,
        -0.56412351,  0.7785562 ,  2.03869387,  1.37818506,  0.21690857],
       [-0.09415033,  0.63635299, -1.20453161, -0.75037488,  0.54697779,
        -0.72333157, -0.309503  , -0.39422845,  0.38114098,  1.0123334 ],
       [-1.11018547,  1.08037599,  1.2086383 , -0.98703427, -0.0170655 ,
         0.2520128 , -2.1380514 , -0.97546021

In [42]:
x[0]

array([ 1.49830411,  1.95394949,  0.53686325, -0.94964002, -1.1491122 ,
        2.75855392, -0.69427643, -0.7667491 ,  0.39207593,  0.37116246])

In [43]:
x[0][4]

-1.149112199175316

In [44]:
x[1:10:2]

array([[-0.30972882, -0.62845745,  1.79749271,  0.24256362,  0.03158585,
         0.6650032 ,  0.37460497,  0.04662303,  0.02566594,  0.49583538],
       [-0.14118574, -1.86607762, -0.2742129 , -0.29064077, -0.53258824,
        -1.61506176,  1.0605039 , -0.62701008, -0.97516007, -2.00734035],
       [-0.09415033,  0.63635299, -1.20453161, -0.75037488,  0.54697779,
        -0.72333157, -0.309503  , -0.39422845,  0.38114098,  1.0123334 ],
       [-1.07865418,  0.09789852, -0.76715252,  0.35907311, -2.08839447,
        -0.64600537, -1.08106689, -0.21003636, -0.07213573, -1.74952047],
       [-0.82814707, -0.67936594, -0.29867512,  1.26006254, -1.05452216,
        -0.2878606 , -0.2564737 , -0.60281275, -1.85333519,  0.34698367]])

In [45]:
x[::,0:4]

array([[ 1.49830411,  1.95394949,  0.53686325, -0.94964002],
       [-0.30972882, -0.62845745,  1.79749271,  0.24256362],
       [ 1.53775336, -0.45566752,  0.54780978, -0.7095128 ],
       [-0.14118574, -1.86607762, -0.2742129 , -0.29064077],
       [ 1.45610833, -0.98545718,  0.8000099 ,  1.32246408],
       [-0.09415033,  0.63635299, -1.20453161, -0.75037488],
       [-1.11018547,  1.08037599,  1.2086383 , -0.98703427],
       [-1.07865418,  0.09789852, -0.76715252,  0.35907311],
       [-0.3342126 ,  0.69850829,  0.64444708, -0.80247277],
       [-0.82814707, -0.67936594, -0.29867512,  1.26006254]])

In [46]:
x=np.ones((5,5))

In [47]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
x[1:-1,1:-1]=0

In [49]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
x[0:-0,0:-0]=2

In [51]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
x[0:-0,0:-0]=2

In [55]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
x=np.array([10,9,8,6,11])

In [57]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [58]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [59]:
y=[7,1,2,3-1]

In [60]:
np.maximum(x,y)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [61]:
np.maximum(x,y)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 